[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[dev]
  command = "npm run dev"
  framework = "#custom"
  port = 5173
  targetPort = 5173 